### ISSUE TITLE
Create test for existing function doesn't work

### ISSUE THREAD

**Issue by skilledDeveloper** [SC5/serverless-mocha-plugin#11]
Trying to create a test for an existing function in a folder.
 
```
$ sls function mocha-create myFunction

Unhandled rejection TypeError: Cannot read property 'split' of undefined
    at .../node_modules/serverless-mocha-plugin/index.js:155:50
    at tryCatcher (.../node_modules/serverless-mocha-plugin/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (.../node_modules/serverless-mocha-plugin/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (.../node_modules/serverless-mocha-plugin/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromiseCtx (.../node_modules/serverless-mocha-plugin/node_modules/bluebird/js/release/promise.js:583:10)
    at Async._drainQueue (.../node_modules/serverless-mocha-plugin/node_modules/bluebird/js/release/async.js:134:12)
    at Async._drainQueues (.../node_modules/serverless-mocha-plugin/node_modules/bluebird/js/release/async.js:139:10)
    at Immediate.Async.drainQueues [as _onImmediate] (.../node_modules/serverless-mocha-plugin/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by mpuittinen** [comment]
Fixed with serverless-mocha-plugin v0.5.4
