### ISSUE TITLE
Serverless `create test` command fails with `Cannot read property 'handler' of undefined`

### ISSUE THREAD

**Issue by kukula** [SC5/serverless-mocha-plugin#52]
Tried to create test for existing function and got error:

```
$ SLS_DEBUG=* sls create test -f getDevices
 
  Type Error ---------------------------------------------
 
     Cannot read property 'handler' of undefined
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'handler' of undefined
    at utils.createTestFolder.then (/home/sls/node_modules/serverless-mocha-plugin/index.js:223:32)
    at tryCatcher (/home/sls/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/sls/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/sls/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/sls/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/sls/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/sls/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/sls/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/sls/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       7.10.0
     Serverless Version: 1.14.0
```

**Comment by laardee** [comment]
@kukula Hi, can you share parts of your `serverless.yml` and `getDevices` function file. I'm interested about 
```yaml
functions:
  getDevices:
    handler: handler.hello
```
in `serverless.yml` and

```js
module.exports.hello = (event, context, callback) => {
```
in handler js file. And the project structure, so I could replicate the issue.

**Comment by kukula** [comment]
Hi @laardee , thank you, and here are the files:
`serverless.yml`:
```yaml
 functions: 
  getDevices: 
     handler: handler.getDevices 
```

`handler.js`:
```js
module.exports.hello = (event, context, callback) => {
```

**Comment by mpuittinen** [comment]
Does you function work and deploy correctly? 
Do you have an indenting error under functions (1 space instead of 2)?

-Mikael

**Comment by kukula** [comment]
@mpuittinen 
yes it is deployed and working. I think there is some problem with camel case name.
when I've tried to create function with `sls create function` with camel cased function name I've got:
 ```js
module.exports. = (event, context, callback) => {
```

**Comment by kukula** [comment]
anyway I found a workaround. thank you!
